### PR TITLE
Update github url for radiant

### PR DESCRIPTION
**Pull request by peterfoley**
The old URL has a message that development has moved.

I'm not too confident that `make` updated the generated files properly. It failed on OSX (`sed` needed a different syntax for `i`), and while it succeeded under Linux, lots of things are changed that probably shouldn't be like dropping `class="uri"` from all the links.

### CODE REVIEW

**Comment by leeper** [comment]
Huh. What version of pandoc are you using?

Regardless, thanks for the update!

**Comment by peterfoley** [comment]
pandoc version is 1.12.2.1, so it's pretty old. It's what `apt-get install pandoc` grabs in Ubuntu 14.04.

**Comment by leeper** [comment]
Thanks.

**Comment by leeper** [comment]
Thanks, again. This is merged.

**Pull request closed without merging**
