### PR TITLE
add latest changes by A Zeileis

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by zeileis** [comment]
Hi everyone. I briefly discussed this PR with @pachadotdev over in the [cran-task-views](https://github.com/cran-task-views/) organization (which will be the new home of all CRAN task view source files).

My feeling is it would be best not to merge this PR because it mostly edits the `README.md` file instead of the `WebTechnologies.ctv` file which should be the file to edit. The reason is that the .ctv file will be converted to the new .md format (i.e., become `WebTechnologies.md`) and then only the latter file should be edited from there.

Maybe it would be easiest to transfer the repository as soon as possible to cran-task-views and then we can take it from there. The same should be done for the [Hydrology task view repository](https://github.com/ropensci/Hydrology) that @boshek already converted to the new format but it is also waiting for the transfer to cran-task-views.

(Note: If you do not want to transfer your repositories to cran-task-views, this is also fine. Then we will preserve the R-Forge history of these task views, rather than your GitHub history, and work from there. This would also be possible.)

Let me know if anything is unclear or if I can help with anything else.

**Comment by boshek** [comment]
@zeileis and @pachadotdev. One option is to use this PR I started here: https://github.com/ropensci/webservices/pull/474

**Comment by zeileis** [comment]
Thanks, Sam @boshek, very much appreciated. This looks good to me.

One minor quibble: `FeedeR` has been archived on CRAN. But this can easily be resolved (before or after merging this PR.)

**Comment by pachadotdev** [comment]
thanks a lot @zeileis and @boshek 
indeed, I updated the ctv file here to match the lastest changes to the repo cran-tasks-view

**Comment by pachadotdev** [comment]
the only part I'm not sure is about rOpenSci's community rules, I'll ask in the morning whereas I'm authorized to transfer this repository and then fork it back to /ropensci (i.e. to make changes at /ropensci and not /cran-tasks-view directly)

**Comment by pachadotdev** [comment]
discussion solved in #576
I did a copy paste in Word, then went line by line checking with control changes to add each of @zeileis changes to @boshek MD document, then checked any possible problem in the transfer (i.e. " , " vs ", " in the text).
the new MD document should be fine

**Pull request closed without merging**
