### PR TITLE
googlesheets now on cran

### PR DESCRIPTION
**Pull request by jennybc**

### CODE REVIEW

**Comment by jennybc** [comment]
Oops. I just saw the contributing guidelines. Shall I close this and try again with Right Way?

**Comment by ashander** [comment]
well, there are several other addpkg issues open they will require the same update. I plan to do those soon and along the way to some needed edits for CRAN so no worries.




thanks for noticing though!



- Jaime

**Comment by ashander** [comment]
Oops! I was confused between this one and webservices. @leeper has been maintaining this one more so I'll let him have final say

**Comment by leeper** [comment]
If you make changes, then rebase your repo, it will squash the commits into this pull request, so no need to close. If you don't feel like doing that, I'll just add the package next time I'm working on this (probably some time next week).

**Pull request closed without merging**
